BEGIN;

DROP TABLE IF EXISTS "rendezvous";
DROP TABLE IF EXISTS "doctors";
DROP TABLE IF EXISTS "expertise";
DROP TABLE IF EXISTS "locations";
DROP TABLE IF EXISTS "patients";



CREATE TABLE IF NOT EXISTS "expertise" (
	"id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	"name"	TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "locations" (
	"id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"postcode"	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "patients" (
	"id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	"firstname" TEXT NOT NULL,
	"lastname"	TEXT NOT NULL,
	"email" TEXT NOT NULL,
	"phone" TEXT NOT NULL,
	"password" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "doctors" (
	"id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	"firstname"	TEXT NOT NULL,
	"lastname"	TEXT NOT NULL,
	"email"	TEXT NOT NULL,
	"phone" TEXT NOT NULL,
	"password"	TEXT NOT NULL DEFAULT 'password',
	"postcode" TEXT NOT NULL DEFAULT '999999',
	"expertise_id" INTEGER NOT NULL,
	FOREIGN KEY("expertise_id") REFERENCES "expertise"("id") ON DELETE CASCADE

);


CREATE TABLE IF NOT EXISTS "rendezvous" (
	"id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
	"date" TEXT NOT NULL,
	"start"	TEXT NOT NULL,
	"end" TEXT NOT NULL,
	"patient_id" INTEGER,
	"doctor_id" INTEGER NOT NULL,
	"location_id" INTEGER NOT NULL,
	FOREIGN KEY("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE,
	FOREIGN KEY("location_id") REFERENCES "locations"("id") ON DELETE CASCADE,
	FOREIGN KEY("doctor_id") REFERENCES "doctors"("id") ON DELETE CASCADE

);

-- DONT FORGET TO CHECK AND COMMIT !!



